---
include:
  - ./configs/dns.yml # Both Internal and external DNS
  - ./configs/kanban.yml
  - ./configs/manage.yml # Torrent API + Cloudflare Proxy
  - ./configs/movies.yml # SD + 4K Instances
  - ./configs/oversee.yml # Jellyseerr + Discord Bot + Wizard
  - ./configs/tv.yml # SD + 4K Instances
  - ./configs/vpn.yml
services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    networks: [highseas]
    command: [--log.level=DEBUG]
    ports:
      - 443:443  # https
      - 80:80
      - 8080:8080  # dashboard (LAN only, do not expose)
    environment:
      # - CF_DNS_API_TOKEN=${CLOUDFLARE_TOKEN}
      - CF_DNS_API_TOKEN=${DYNDNS_CLOUDFLARE}
      - DOMAIN=${DOMAIN}
      - SHORT_DOMAIN=${SHORT_DOMAIN}
      - EMAIL=${EMAIL}
    extra_hosts: [host.docker.internal:host-gateway]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./configs/traefik/static-cfg.yaml:/etc/traefik/static-cfg.yaml
      - ./configs/traefik/certs:/var/traefik/certs:rw
    restart: unless-stopped
  sablier:
    image: sablierapp/sablier:1.8.1
    command: [start, --provider.name=docker]
    volumes: [/var/run/docker.sock:/var/run/docker.sock]
    networks: [highseas]
    restart: unless-stopped
  torrent:
    extends:
      file: ./configs/torrent.yml
      service: torrent
    depends_on:
      - vpn  # Otherwise piaconf can be empty/out-of-date
networks:
  highseas:
    driver: bridge
