version: "3"

# The config automatically sets up the following:
#   - Prowlarr: communicates with torrents sites
#   - Sonarr: Manages TV Shows and requests missing/better ones
#   - Radarr: Manages Movies and requests missing/better ones
#   - Plex: Media hoster for movies & tv shows
#   - Transmission: Torrent downloader
#   - Requestrr: Discord bot for Sonarr & Radarr
#   - Gluetun: Generic VPN container that cloaks services that need it
#     (everything except plex)
#
# You can configure the services by accessing their Web UIs:
#   - Plex: localhost:32400/web
#   - Prowlarr: localhost:9696
#   - Radarr: localhost:7878
#   - Sonarr: localhost:8989
#   - Sonarr: localhost:9091
#   - Requestrr: localhost:4545
#
# Basic Variables can be set by copying the env-example file
# to .env and configuring the variables there.
#
# Alternatively, set your variables directly in this file.

services:
  privateer-vpn:
    image: qmcgaw/gluetun:latest
    container_name: privateer-vpn
    cap_add:
      - NET_ADMIN
    volumes:
      - gluetun:/gluetun
    ports:
      # Prowlarr ports:
      - 9696:9696
      # Transmission ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      # Sonarr ports:
      - 8989:8989
      # Radarr ports:
      - 7878:7878
      # Requestrr ports:
      - 4545:4545
      # Flaresolverr ports:
      - "${PORT:-8191}:8191"
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWD}
      - REGION=${VPN_REGION}
    restart: unless-stopped

  privateer-prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: privateer-prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - prowlarr-conf:/config
      - ${TORRENT_TMP_DIR}:/downloads
    network_mode: service:privateer-vpn
    restart: unless-stopped

  privateer-proxy:
    image: flaresolverr/flaresolverr:latest
    container_name: privateer-proxy
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    network_mode: service:privateer-vpn
    restart: unless-stopped

  privateer-torrent:
    image: linuxserver/transmission:latest
    container_name: privateer-torrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - torrent-conf:/config
      - ${TORRENT_TMP_DIR}:/downloads
    network_mode: service:privateer-vpn
    restart: unless-stopped

  privateer-sonarr:
    image: linuxserver/sonarr:latest
    container_name: privateer-sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - sonarr-conf:/config
      - ${TV_DIR}:/tv
      - ${TORRENT_TMP_DIR}:/downloads
    network_mode: service:privateer-vpn
    restart: unless-stopped

  privateer-radarr:
    image: linuxserver/radarr:latest
    container_name: privateer-radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - radarr-conf:/config
      - ${MOVIE_DIR}:/movies
      - ${TORRENT_TMP_DIR}:/downloads
    network_mode: service:privateer-vpn
    restart: unless-stopped

  privateer-plex:
    image: linuxserver/plex:latest
    container_name: privateer-plex
    network_mode: bridge
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "5353:5353/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
    environment:
      - PUID=1000
      - PGID=1000
      - NVIDIA_VISIBLE_DEVICES=all
      - VERSION=latest
      - TZ=${TIMEZONE}
    volumes:
      - plex-conf:/config
      - ${MOVIE_DIR}:/movies
      - ${TV_DIR}:/tv
    restart: unless-stopped

  privateer-discord:
    image: linuxserver/requestrr:latest
    container_name: privateer-discord
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - requestrr-conf:/config
    network_mode: service:privateer-vpn
    restart: unless-stopped

volumes:
  gluetun:
  prowlarr-conf:
  torrent-conf:
  sonarr-conf:
  radarr-conf:
  requestrr-conf:
  plex-conf:
