---
http:
  routers:
    plex:
      rule: Host(`plex.{{ env "DOMAIN" }}`) || Host(`plex.{{ env "SHORT_DOMAIN" }}`)
      service: plex
      tls:
        certResolver: cloudflare
        domains:
          - main: ['plex.{{ env "DOMAIN" }}', 'plex.{{ env "SHORT_DOMAIN" }}']
      entryPoints: [websecure]
    kanban:
      rule: Host(`kanban.{{ env "DOMAIN" }}`)
      service: kanban
      entryPoints: [websecure]
      tls:
        certResolver: cloudflare
      middlewares: [kanban-sablier@file]
    jellyfin:
      rule: Host(`watch.{{ env "DOMAIN" }}`) || Host(`watch.{{ env "SHORT_DOMAIN" }}`)
      service: jellyfin
      tls:
        certResolver: cloudflare
        domains:
          - main: ['watch.{{ env "DOMAIN" }}', 'watch.{{ env "SHORT_DOMAIN" }}']
      entryPoints: [websecure]
    # jellyfin:
    #   rule: Host(`watch.{{ env "DOMAIN" }}`)
    #   service: jellyfin
    #   entryPoints: [websecure]
    #   tls:
    #     certResolver: cloudflare
    #   middlewares: [jelly-sablier@file]
  services:
    plex:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:32400
    kanban:
      loadBalancer:
        servers:
          - url: http://kanban:1337
    jellyfin:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8096
  middlewares:
    kanban-sablier:
      plugin:
        sablier:
          group: kanban
          dynamic:
            displayName: Kanban
            refreshFrequency: 2s
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 5m
    # jelly-sablier:
    #   plugin:
    #     sablier:
    #       group: home
    #       dynamic:
    #         displayName: Jellyfin
    #         refreshFrequency: 2s
    #         theme: ghost
    #       sablierUrl: http://sablier:10000
    #       sessionDuration: 3m
