---
services:
  torrent:
    build:
      context: ./qbit-pia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - WEBUI_PORT=4242
      - TORRENTING_PORT=54990
    # No port configuration as vpn is used as the network for this container
    volumes:
      - ./qbittorrent:/config
      - ${TORRENT_TMP_DIR}:/downloads
      - ./gluetun/piaportforward.json:/tmp/piaportforward.json  # Sync Torrent port config from PIA
    restart: unless-stopped
